### ISSUE TITLE
Hitting the "back" button closes the app

### ISSUE THREAD

**Issue by mitchhentges** [stevelyall/project-ernie-app#20]
It's preferred that hitting the "android back"  button goes back a screen.

**Comment by chrisfosterelli** [comment]
+1 That's super confusing behaviour.

**Comment by mitchhentges** [comment]
Yeah jeez fix this or I'm not buying any of your future products or DLC

**Comment by mitchhentges** [comment]
DICE pls

**Comment by stevelyall** [comment]
Thanks guys. It makes sense to come up with a better solution for this. As participants aren't meant to be able to go back to the previous question, would more intuitive behaviour be to resume at the home screen? Perhaps at the last question completed?

**Comment by chrisfosterelli** [comment]
How come participants aren't meant to go back? The user may have made a mistake, I can't see a detrimental effect of allowing the user to go back in the questions. 

But yes, if that was an absolute requirement then maybe having the "back" button go to the homepage or something would make more sense, but that'd still be relatively unintuitive for a user. Perhaps pressing "back" brings up a prompt asking them if they want to exit the survey? That way the user would be aware that pressing back doesn't do what they thought, but they won't accidentally drop out of the survey.

**Comment by stevelyall** [comment]
They don't want people going and changing their answers to previous questions once they've seen later questions in the survey. 

I like the idea of am "are you sure?" alert so people don't quit and lose their progress by accident. Good call!
