### ISSUE TITLE
Remove the "next" button from the survey

### ISSUE THREAD

**Issue by mitchhentges** [stevelyall/project-ernie-app#24]
This depends on "go back" functionality.
Things would be 10% less painful if I didn't have to tap some number, then tap next. If there was only one tap per page, that would be #1.

**Comment by stevelyall** [comment]
I agree with you that this would be easier. The client preferred two clicks so that users can change their answers, but it may be something they're open to!

**Comment by mitchhentges** [comment]
That's why the "back" functionality is required first. Once users can go "back" if they change their minds, the better.
Perhaps "Next" should remain, but it should be automatically triggered when a number is selected.

**Comment by stevelyall** [comment]
I'd be open to making it easier to complete a question with fewer clicks, though participants aren't meant to be able to be able to change their minds once they have finalized their answer. 

I feel like automatically triggering "Next" wouldn't give them the opportunity to change their selection before continuing?
