### ISSUE TITLE
Hitting the back button, then re-opening the app restarts from the beginning

### ISSUE THREAD

**Issue by mitchhentges** [stevelyall/project-ernie-app#25]
Having to restart the survey really sucks.

**To reproduce:**
1. Start the app
2. Start a survey
3. Do some questions
4. Hit the "android back" button (depends on #20 still being an issue)
5. Hit the "android app chooser" button, reopen ERA
6. I NEED TO START FROM THE BEGINNING WHAT THE BALLS

**Comment by stevelyall** [comment]
future DLC will let you continue from where you left off, as long as you're returning to the survey within a specific amount of time- is that more reasonable?
