### ISSUE TITLE
Selecting a number has a uncentered circle

### ISSUE THREAD

**Issue by chrisfosterelli** [stevelyall/project-ernie-app#30]
Model: Nexus 5

Holding over a number element brings up the gray circle, but the gray circle is not centred on the number and it looks off.

![screenshot_2015-04-03-22-01-03](https://cloud.githubusercontent.com/assets/2072672/6991514/932bc04e-da4e-11e4-9d90-cb3c056e34c4.png)

**Comment by stevelyall** [comment]
Thanks Chris- this should be solved for the next update. It's not as pretty without the shadow, but doesn't look as weird when you hold down the button now. I'm open to suggestions on how to fix while keeping the drop shadow :)

**Comment by chrisfosterelli** [comment]
Np!
